"use client";

import { useState } from "react";
import Image from "next/image";
import Underline from "../../../components/Underline";
import { FiPlus, FiMinus } from "react-icons/fi";

const Faq = () => {
  const [activeIndex, setActiveIndex] = useState(0);

  const faqItems = [
    {
      question: "Are these AI tools really free?",
      answer:
        "Yes! All our AI tools have a generous free tier. You can use them with basic limits at no cost. For unlimited access and advanced features, check out our Pro plan.",
    },
    {
      question: "What's the difference between free and Pro access?",
      answer:
        "Free access includes basic usage limits (e.g., 5 analyses per day). Pro access removes all limits, adds advanced AI features, priority processing, and access to exclusive tools.",
    },
    {
      question: "How accurate is the PageSpeed analysis?",
      answer:
        "Our PageSpeed Insights tool uses Google's Lighthouse technology, the same engine that powers Google's official PageSpeed Insights. Results are highly accurate and actionable.",
    },
    {
      question: "Can I use the generated content commercially?",
      answer:
        "Absolutely! All content generated by our AI tools is yours to use however you like—for your website, social media, marketing materials, and more.",
    },
    {
      question: "Do I need technical knowledge to use these tools?",
      answer:
        "Not at all! Our tools are designed to be user-friendly. Simply enter your website URL or content brief, and our AI handles the rest.",
    },
    {
      question: "How often are the tools updated?",
      answer:
        "We continuously improve our AI models and add new features. Major updates are released monthly, with bug fixes and improvements pushed weekly.",
    },
    {
      question: "Can I integrate these tools with my workflow?",
      answer:
        "Yes! Pro users get access to our API for seamless integration with your existing tools and workflows. Contact us for custom integration support.",
    },
  ];

  const toggleAccordion = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section className="py-20 px-5  w-full box-border text-left">
      <div className="w-full max-w-6xl mx-auto">
        <div className="mb-16 w-full">
          <span className="block text-xs font-semibold text-[#9AA1AE] uppercase tracking-wider mb-4 text-left w-full">
            FREQUENTLY ASKED QUESTIONS
          </span>
          <div className="relative w-full flex items-start">
            <div className="flex-1">
              <h2 className="text-[46px] font-light text-black m-0 leading-snug text-left relative inline-block max-w-[80%]">
                AI Tools{" "}
                <span className="relative text-[42px] inline-block font-hello font-normal">
                  Questions Answered.
                  <div className="absolute -bottom-3 md:-bottom-3 lg:-bottom-4 left-1/2 -translate-x-1/2 md:scale-x-[1.2] w-full">
                    <Underline color="#006a04ff" width="100%" thickness="4" />
                  </div>
                </span>
              </h2>
            </div>
            <div className="ml-5 -mt-2.5 flex-shrink-0">
              <Image
                src="/images/questionMarkDoodle.svg"
                alt="Question mark doodle"
                width={120}
                height={120}
                className="relative"
              />
            </div>
          </div>
        </div>

        <div className="w-full">
          {faqItems.map((item, index) => (
            <div key={index} className="mb-2.5">
              <button
                onClick={() => toggleAccordion(index)}
                className={`w-full text-left py-5 text-[26px] font-normal transition-colors duration-300 flex justify-between items-start ${
                  activeIndex === index ? "text-black" : "text-[#333]"
                }`}
              >
                <span className="text-left pr-4">{item.question}</span>
                <span
                  className={`text-[#666] transition-transform duration-300 ml-5 flex-shrink-0 flex items-center justify-center text-2xl ${
                    activeIndex === index ? "rotate-0" : "rotate-0"
                  }`}
                >
                  {activeIndex === index ? <FiMinus /> : <FiPlus />}
                </span>
              </button>
              {activeIndex === index && item.answer && (
                <div className="pb-5 text-[#666] text-lg leading-relaxed text-left w-full">
                  <p>{item.answer}</p>
                </div>
              )}
              <div className="h-px bg-gray-200 w-full" />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Faq;
